name: POC18 CI Workflow

on:
  push:
    branches:
      - dev
       - main

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev

    steps:
      - name: Deploy to dev EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Connected to EC2"

            # Clone repo and checkout dev branch
            git clone https://github.com/vardhanreddy2003/poc18.git
            cd poc18
            git checkout dev
             #dev
            # Pull latest changes from dev branch
            git pull origin dev

            # Install and start NGINX
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Copy index.html to NGINX's default directory
            sudo cp index.html /var/www/html/

            # Restart NGINX to apply the changes
            sudo systemctl restart nginx

            echo "Deployment to dev server complete"

  deploy-test:
    name: Deploy to test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    environment: test

    steps:
      - name: Deploy to test EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Connected to EC2"

            # Clone repo and checkout test branch
            git clone https://github.com/vardhanreddy2003/poc18.git
            cd poc18
            git checkout test

            # Pull latest changes from test branch
            git pull origin test

            # Install and start NGINX
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Copy index.html to NGINX's default directory
            sudo cp index.html /var/www/html/

            # Restart NGINX to apply the changes
            sudo systemctl restart nginx

            echo "Deployment to test server complete"

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:
      - name: Deploy to prod EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Connected to EC2"

            # Clone repo and checkout main branch
            git clone https://github.com/vardhanreddy2003/poc18.git
            cd poc18
            git checkout main

            # Pull latest changes from main branch
            git pull origin main

            # Install and start NGINX
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Copy index.html to NGINX's default directory
            sudo cp index.html /var/www/html/

            # Restart NGINX to apply the changes
            sudo systemctl restart nginx

            echo "Deployment to prod server complete"
